export const FETCH_LIST_LOADING = "report/FETCH_LIST_LOADING";
export const FETCH_LIST_COMPLETED = "report/FETCH_LIST_COMPLETED";
export const FETCH_LIST_FAILED = "report/FETCH_LIST_FAILED";
export const SET_LISTREPORT = "report/SET_LISTREPORT";
export const FETCH_REPORTDETAIL_COMPLETED = "report/FETCH_REPORTDETAIL_COMPLETED";
export const FETCH_REPORTDETAIL_FAILED = "report/FETCH_REPORTDETAIL_FAILED";
export const SET_LOADING_PAGE = "report/SET_LOADING_PAGE";