export const FETCH_LIST_LOADING = "limitpurchase/FETCH_LIST_LOADING";
export const FETCH_LIST_COMPLETED = "limitpurchase/FETCH_LIST_COMPLETED";
export const FETCH_LIST_FAILED = "limitpurchase/FETCH_LIST_FAILED";
export const SET_LISTLIMITPURCHASE = "limitpurchase/SET_LISTLIMITPURCHASE";
export const SET_CREATEUPDATELIMITPURCHASE = "limitpurchase/SET_CREATEUPDATELIMITPURCHASE";

export const SAVE_LIMITPURCHASECOMPLETED = "limitpurchase/SAVE_LIMITPURCHASECOMPLETED";
export const SAVE_LIMITPURCHASEFAILED = "limitpurchase/SAVE_LIMITPURCHASEFAILED";
export const SAVE_BULKLIMITPURCHASECOMPLETED = "limitpurchase/SAVE_BULKLIMITPURCHASECOMPLETED";
export const SAVE_BULKLIMITPURCHASEFAILED = "limitpurchase/SAVE_BULKLIMITPURCHASEFAILED";
export const SET_HAVELIMITPURCHASE = "limitpurchase/SET_HAVELIMITPURCHASE";
export const GET_LIMITPURCHASE = "limitpurchase/GET_LIMITPURCHASE";
export const SET_ISSAVELOADING = "limitpurchase/SET_ISSAVELOADING";
export const SET_LOADING_PAGE = "limitpurchase/SET_LOADING_PAGE";
export const SET_IS_DELETE_LOADING = "limitpurchase/SET_IS_DELETE_LOADING";
export const SET_IS_PAGINATE_LOADING = "limitpurchase/SET_IS_PAGINATE_LOADING";

export const SAVE_BULKACTIONPURCHASECOMPLETED = "limitpurchase/SAVE_BULKACTIONPURCHASECOMPLETED";
export const SAVE_BULKACTIONPURCHASEFAILED = "limitpurchase/SAVE_BULKACTIONPURCHASEFAILED";